name: Premerge

on:
  pull_request:
    branches: [ "main" ]

env:
  CMAKE_PRESET: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v3

    - uses: pre-commit/action@v3.0.1

    - name: Install LLVM
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 20
        sudo apt install libmlir-20-dev mlir-20-tools

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true

    - name: Configure CMake
      run: cmake --preset ${{env.CMAKE_PRESET}}

    - name: Build
      run: cmake --build --preset ${{env.CMAKE_PRESET}}

    - name: Test
      run: |
        ctest --preset ${{env.CMAKE_PRESET}} -E integration-tests
        # only run the integration-tests with verbose so we can see the
        # whole output which includes which python scripts passed
        ctest --preset ${{env.CMAKE_PRESET}} -R integration-tests -V

